Use Ventas
ALTER TABLE Detalle
ADD CONSTRAINT FK_Detalle_Productos
FOREIGN KEY (Cod) REFERENCES Productos(Cod)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
CONSTRAINT FK_Detalle_Facturar
FOREIGN KEY (nFactura) REFERENCES Facturar(nFactura)
	ON UPDATE CASCADE
	ON DELETE CASCADE
	